version: '3.9'

services:
  postgres:
    image: 'postgres'
    ports:
      - '2345:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'garudahacks'
    volumes:
      - .:/usr/src/app
  server:
    build: .
    ports:
      - '9999:9999'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/garudahacks?schema=public'
      JWT_SECRET: 'serpentgan'
      SALT_ROUNDS: '16'
    depends_on:
      - postgres

volumes: 
  data: {}
